// <auto-generated />
namespace NAPASTUDENT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ThemThongTinChoHoatDong : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ThemThongTinChoHoatDong));
        
        string IMigrationMetadata.Id
        {
            get { return "201810130419175_ThemThongTinChoHoatDong"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
