// <auto-generated />
namespace NAPASTUDENT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ThanhVienDonVi_ThayDoi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ThanhVienDonVi_ThayDoi));
        
        string IMigrationMetadata.Id
        {
            get { return "201908181159161_ThanhVienDonVi_ThayDoi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
