// <auto-generated />
namespace NAPASTUDENT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Lop_Them_AnhBiaLop_Xoa_SoLuong : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Lop_Them_AnhBiaLop_Xoa_SoLuong));
        
        string IMigrationMetadata.Id
        {
            get { return "201908081031159_Lop_Them_AnhBiaLop_Xoa_SoLuong"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
