// <auto-generated />
namespace NAPASTUDENT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Them_ThongBaoHoatDong : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Them_ThongBaoHoatDong));
        
        string IMigrationMetadata.Id
        {
            get { return "201907161627563_Them_ThongBaoHoatDong"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
